### ISSUE TITLE
Spanner example failed to build

### ISSUE THREAD

**Issue by dexterchan** [GoogleCloudPlatform/java-docs-samples#799] opened 2017-08-09 15:52 UTC
## In which file did you encounter the issue?
java-docs-samples/spanner/cloud-client

### Did you change the file? If so, how?
No

## Describe the issue
failed to build
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project spanner-google-cloud-samples: Compilation failure
[ERROR] /Users/dexter/Downloads/java-docs-samples/spanner/cloud-client/src/main/java/com/example/spanner/QuickstartSample.java:[21,32] cannot access com.google.cloud.spanner.DatabaseClient
[ERROR] bad class file: /Users/dexter/.m2/repository/com/google/cloud/google-cloud-spanner/0.21.1-beta/google-cloud-spanner-0.21.1-beta.jar(/com/google/cloud/spanner/DatabaseClient.class)
[ERROR] unable to access file: java.util.zip.ZipException: invalid distance too far back
[ERROR] Please remove or make sure it appears in the correct subdirectory of the classpath.

**Comment by lesv** [comment] 2017-08-09 21:10
I've built and tested this a couple times today.  What environment do you have? (java version; os version; etc)

**Comment by dexterchan** [comment] 2017-08-09 21:34
Mac OS 10.12.6
Jdk1.8.11

Sent from my iPad

On 9 Aug 2017, at 22:10, Les Vogel <notifications@github.com<mailto:notifications@github.com>> wrote:


I've built and tested this a couple times today. What environment do you have? (java version; os version; etc)

**Comment by lesv** [comment] 2017-08-12 01:06
Wow - That is very old.  My current Java is:  java version "1.8.0_131"  Looking at http://www.oracle.com/technetwork/java/javase/8u-relnotes-2225394.html, 144 seems to be current.

**Comment by jabubake** [comment] 2017-08-14 17:50
Can you state what version of the Spanner client library you are attempting to use ? Please use the latest [pom.xml](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/spanner/cloud-client/pom.xml).

**Comment by jabubake** [comment] 2017-10-10 19:25
@dexterchan : closing this issue, as we were not able to reproduce.. Please open a fresh issue if you are still running into issues.

**Closed by jabubake** 2017-10-10 19:25 UTC
