### ISSUE TITLE
Need to fix dependency issues

### ISSUE THREAD

**Issue by suraj-pasuparthy** [GoogleCloudPlatform/java-docs-samples#7738] opened 2023-03-13 16:08 UTC
## In which file did you encounter the issue?

spanner/opencensus/src/main/java/com/example/spanner/opencensus/CaptureGrpcMetric.java

### Did you change the file? If so, how?

No

## Describe the issue

The GRPC metrics no longer show up with the latest version of spanner library.
After testing, it was found that we need to change the dependencies for the metrics to work.
<dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-spanner</artifactId>
      <version>6.37.0</version>
    </dependency>
<dependency>
      <groupId>io.opencensus</groupId>
      <artifactId>opencensus-api</artifactId>
      <version>0.26.0</version>
    </dependency>
    <dependency>
      <groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-java</artifactId>
      <version>3.22.1</version>
    </dependency>
    <dependency>
      <groupId>io.opencensus</groupId>
      <artifactId>opencensus-impl</artifactId>
      <version>0.26.0</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>io.opencensus</groupId>
      <artifactId>opencensus-contrib-zpages</artifactId>
      <version>0.26.0</version>
    </dependency>
    <dependency>
      <groupId>io.opencensus</groupId>
      <artifactId>opencensus-exporter-trace-stackdriver</artifactId>
      <version>0.26.0</version>
    </dependency>
    <dependency>
      <groupId>io.opencensus</groupId>
      <artifactId>opencensus-exporter-stats-stackdriver</artifactId>
      <version>0.26.0</version>
    </dependency>
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-census</artifactId>
      <version>1.53.0</version>
    </dependency>
    <dependency>
      <groupId>io.opencensus</groupId>
      <artifactId>opencensus-contrib-grpc-metrics</artifactId>
      <version>0.26.0</version>
    </dependency>

**Comment by kolea2** [comment] 2023-03-29 16:20
Reassigning to @olavloite for triage.

**Comment by olavloite** [comment] 2023-04-03 14:03
@rajatbhatta Would you mind taking a look at this?

**Comment by rajatbhatta** [comment] 2023-05-18 10:13
As per internal documentation, most likely the cause of the issue is misconfiguration on the customer's end like not including critical dependency like `grpc-census` in their application. We don't have to modify any dependencies from the client libraries side. Thanks! Closing.

**Closed** 2023-05-22 07:30 UTC
Labels: type: cleanup, priority: p2, api: spanner, samples
