### ISSUE TITLE
Dataflow Spanner IO Tests are failing

### ISSUE THREAD

**Issue by nnegrey** [GoogleCloudPlatform/java-docs-samples#2025] opened 2020-01-23 20:56 UTC
PR: https://github.com/GoogleCloudPlatform/java-docs-samples/pull/2024
update apache_beam.version to v2.18.0

https://source.cloud.google.com/results/invocations/4bd9843f-2dbb-4654-a228-b489df8eee00/targets

**Comment by skuruppu** [comment] 2020-02-05 03:51
@olavloite, would you be able to take a look at this?

**Comment by olavloite** [comment] 2020-02-12 16:20
This issue is being caused by conflicting versions of `io.opencensus:opencensus-api` being imported by the BigTable client and Spanner client in `beam-sdks-java-io-google-cloud-platform`. BigTable wants 0.15.0 and Spanner 0.18.0. Because they are both at the same level in the project hierarchy, and BigTable is included before Spanner, the version specified by BigTable is resolved and used. Excluding the BigTable client in the example is the quick fix for this. I've edited that in the PR for the version upgrade to do this, and this does remove the original error. The build is however currently failing on (conflicting?) NOT_FOUND and ALREAD_EXISTS errors for the test database.

I've also created an issue with Beam for this: https://issues.apache.org/jira/browse/BEAM-9304

**Closed** 2020-02-16 20:12 UTC
Labels: :rotating_light:, api: spanner, priority: p1, type: bug
