### ISSUE TITLE
500 server error on URL after deploying application to GAE

### ISSUE THREAD

**Issue by chessegg** [GoogleCloudPlatform/java-docs-samples#3096] opened 2020-06-09 20:01 UTC
#Describe the issue
Hello! I followed the Springboot Hello-world example code using these links (https://cloud.google.com/appengine/docs/standard/java11/building-app/writing-web-service) (https://cloud.google.com/appengine/docs/standard/java11/building-app/deploying-web-service) and the Github code found here for the springboot hello-world application. 

I was actually able to successfully deploy on GAE, but when I go to the link that was created, it keeps saying that there is a 500 server error (screenshot attached). The 500 error being thrown is visible in Cloud Tracing on Google Cloud. I named my service "testing" instead of using the default service, but this shouldn't make a difference.

I tried deploying via Maven plugin and via deploying the jar file directly, but both had the server error. I also tried moving the JAR file to the same directory as my app.yaml file so that I could try to deploy using "gcloud app deploy", but it also ended up deploying successfully on GAE but having the server error when I visited the URL.

Because the application deploys successfully to GAE no matter how I deploy it, I'm thinking that there is probably some small problem with the application itself being outdated somewhere and that there is some server issue because of it. Would you possibly happen to have an idea of what is causing this error?

Thank you!

Craig

![Screenshot 2020-06-09 at 10 37 27 AM](https://user-images.githubusercontent.com/43458707/84193760-cb1cf680-aa50-11ea-9aaa-4b4b43a1c640.png)
![Screenshot 2020-06-09 at 10 36 53 AM](https://user-images.githubusercontent.com/43458707/84193762-cbb58d00-aa50-11ea-8775-3a8b84045776.png)

**Comment by averikitsch** [comment] 2020-06-12 19:06
Closing due to not being able to reproduce. Please re-open if you continue to experience this issue and have more logs.

**Closed by averikitsch** 2020-06-12 19:06 UTC
Labels: api: appengine, priority: p1, type: bug
