### ISSUE TITLE
en-token.bin file not working apparantly.

### ISSUE THREAD

**Issue by DushyantShukla** [GoogleCloudPlatform/java-docs-samples#240] opened 2016-05-13 15:49 UTC
Use of english token model (en-token.bin) downloaded from the given source resulted in  null pointer exception. Instead I downloaded the file from http://maven.tamingtext.com/opennlp-models/models-1.5/ to make the sample program run accordingly.

**Comment by tswast** [comment] 2016-05-13 19:24
This is for the [Google Cloud Vision API Text Detection sample](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/vision/text), correct?

**Comment by DushyantShukla** [comment] 2016-05-14 08:11
Yeah.

**Comment by gguuss** [comment] 2017-01-19 19:10
I just tested this with the model referenced in the README and was unable to reproduce the issue, closing.

**Closed by gguuss** 2017-01-19 19:10 UTC
Labels: bug
