### ISSUE TITLE
java.lang.AbstractMethodError: com.google.api.gax.grpc.GrpcCallContext.getTracer()Lcom/google/api/gax/tracing/ApiTracer;

### ISSUE THREAD

**Issue by Mouzitoto** [GoogleCloudPlatform/java-docs-samples#1377] opened 2019-04-08 14:04 UTC
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/vision/cloud-client/src/main/java/com/example/vision/QuickstartSample.java

### Did you change the file? If so, how?

I get the credentials that way:
```
ClassPathResource resource = new ClassPathResource("/asiq-service-account-key.json");

Credentials myCredentials = ServiceAccountCredentials.fromStream(resource.getInputStream());

ImageAnnotatorSettings imageAnnotatorSettings =
        ImageAnnotatorSettings.newBuilder()
                .setCredentialsProvider(FixedCredentialsProvider.create(myCredentials))
                .build();

ImageAnnotatorClient vision = ImageAnnotatorClient.create(imageAnnotatorSettings);
```

## Describe the issue

After evaluating that code:
`
BatchAnnotateImagesResponse response = vision.batchAnnotateImages(requests);
`

im getting error:
```
java.lang.AbstractMethodError: com.google.api.gax.grpc.GrpcCallContext.getTracer()Lcom/google/api/gax/tracing/ApiTracer;
```

Stacktrace:
```
Caused by: java.lang.AbstractMethodError: com.google.api.gax.grpc.GrpcCallContext.getTracer()Lcom/google/api/gax/tracing/ApiTracer;
	at com.google.api.gax.retrying.BasicRetryingFuture.handleAttempt(BasicRetryingFuture.java:141) ~[gax-1.42.0.jar:1.42.0]
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.handle(CallbackChainRetryingFuture.java:135) ~[gax-1.42.0.jar:1.42.0]
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.run(CallbackChainRetryingFuture.java:117) ~[gax-1.42.0.jar:1.42.0]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435) ~[guava-20.0.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900) ~[guava-20.0.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:634) ~[guava-20.0.jar:na]
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:98) ~[guava-20.0.jar:na]
	at com.google.common.util.concurrent.ForwardingListenableFuture.addListener(ForwardingListenableFuture.java:45) ~[guava-20.0.jar:na]
	at com.google.api.gax.retrying.CallbackChainRetryingFuture.setAttemptFuture(CallbackChainRetryingFuture.java:93) ~[gax-1.42.0.jar:1.42.0]
	at com.google.api.gax.rpc.AttemptCallable.call(AttemptCallable.java:89) ~[gax-1.42.0.jar:1.42.0]
	at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:63) ~[gax-1.42.0.jar:1.42.0]
	at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:41) ~[gax-1.42.0.jar:1.42.0]
	at com.google.api.gax.rpc.UnaryCallable$1.futureCall(UnaryCallable.java:126) ~[gax-1.42.0.jar:1.42.0]
	at com.google.api.gax.rpc.UnaryCallable.futureCall(UnaryCallable.java:87) ~[gax-1.42.0.jar:1.42.0]
	at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112) ~[gax-1.42.0.jar:1.42.0]
	at com.google.cloud.vision.v1.ImageAnnotatorClient.batchAnnotateImages(ImageAnnotatorClient.java:210) ~[google-cloud-vision-1.66.0.jar:1.66.0]
	at com.google.cloud.vision.v1.ImageAnnotatorClient.batchAnnotateImages(ImageAnnotatorClient.java:187) ~[google-cloud-vision-1.66.0.jar:1.66.0]
```

**Comment by Mouzitoto** [comment] 2019-04-08 14:08
I'm using jdk1.8.0_171
Have tried this with "no-role" service account key and "owner-role" service account key.

**Comment by Mouzitoto** [comment] 2019-04-08 14:23
Updated to jdk1.8.0_201, still having this error.

**Comment by cyberpwnn** [comment] 2019-05-19 09:48
This is also happening with cloud tts. at .synthesizeSpeech(...). Unusable.

**Comment by rvanderwerf** [comment] 2019-05-21 20:03
I have the same issue. I think it's a library conflict of some sort with rxjava.

**Comment by gguuss** [comment] 2019-06-12 19:08
Ack, I'm looking into this.

**Comment by jatins** [comment] 2019-06-23 16:35
Getting this with `google-cloud-pubsub:1.78.0` too

```
Caused by: java.lang.AbstractMethodError: com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.needsCredentials()Z
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:157)
	at com.google.cloud.pubsub.v1.stub.GrpcSubscriberStub.create(GrpcSubscriberStub.java:263)
	at com.google.cloud.pubsub.v1.stub.SubscriberStubSettings.createStub(SubscriberStubSettings.java:241)
	at com.google.cloud.pubsub.v1.SubscriptionAdminClient.<init>(SubscriptionAdminClient.java:178)
```

**Comment by gguuss** [comment] 2019-06-25 21:29
Reassigning to Kurtis as I'll be OOO starting this week

**Comment by kurtisvg** [comment] 2019-06-26 17:20
@Mouzitoto - As far as I can tell, the current sample is now working correctly, and doesn't throw the error even with the modifications. 

Everyone else - the most likely cause of the problem is a conflict in dependencies somewhere in your `pom.xml`. If you are still having issues, please make sure you are using the most recent versions of any dependencies. If this doesn't fix the issue, please feel free to update the this issue with your `pom.xml` and we can see if we can help.

**Closed by kurtisvg** 2019-06-26 17:20 UTC
Labels: type: question

**Comment by hemaldaha** [comment] 2020-06-25 20:30
Using the following dependencies and still getting the issue. 
 <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-storage</artifactId>
            <version>1.110.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.firebase</groupId>
            <artifactId>firebase-admin</artifactId>
            <version>6.14.0</version>
        </dependency>

Exception in thread "main" java.lang.AbstractMethodError: com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.withExecutor(Ljava/util/concurrent/Executor;)Lcom/google/api/gax/rpc/TransportChannelProvider;
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:140)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:123)
	at com.google.cloud.firestore.spi.v1.GrpcFirestoreRpc.<init>(GrpcFires
.

**Comment by kurtisvg** [comment] 2020-06-25 20:45
Hi @hemaldaha,

This issue is over a year old without any updates - please verify your dependencies aren't conflicted, and if not please open a new issue and make sure to all relevant information.

**Comment by hemaldaha** [comment] 2020-06-25 21:03
Well thats all i have in the dependency list.
