### ISSUE TITLE
Exception in thread "main" com.google.api.gax.rpc.ResourceExhaustedException: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'speech.googleapis.com/default_requests' and limit 'DefaultRequestsPerMinutePerProject' of service 'speech.googleapis.com' for consumer 'project_number:

### ISSUE THREAD

**Issue by asurjit79** [GoogleCloudPlatform/java-docs-samples#1461] opened 2019-06-12 12:45 UTC
## In which file did you encounter the issue?
QuickSample.java

### Did you change the file? If so, how?
No

## Describe the issue

I am getting the above mentioned issue when I try to run this programme. The detailed exception is pasted below 

Jun 12, 2019 12:53:03 PM com.google.auth.oauth2.DefaultCredentialsProvider warnAboutProblematicCredentials
WARNING: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
Exception in thread "main" com.google.api.gax.rpc.ResourceExhaustedException: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'speech.googleapis.com/default_requests' and limit 'DefaultRequestsPerMinutePerProject' of service 'speech.googleapis.com' for consumer 'project_number:764086051850'.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:57)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1056)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1139)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:958)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:748)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:507)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:482)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:699)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.speech.v1.SpeechClient.recognize(SpeechClient.java:244)
		at com.google.cloud.speech.v1.SpeechClient.recognize(SpeechClient.java:208)
		at com.example.speech.QuickstartSample.main(QuickstartSample.java:62)
Caused by: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'speech.googleapis.com/default_requests' and limit 'DefaultRequestsPerMinutePerProject' of service 'speech.googleapis.com' for consumer 'project_number:764086051850'.
	at io.grpc.Status.asRuntimeException(Status.java:532)
	... 23 more

I set the credential file as well as suggested in the docs
export GOOGLE_APPLICATION_CREDENTIALS=/Users/asurjit/Downloads/Amar1979-ba0acd0298c9.json 

Further, I ran the gcloud auth list command as well and the service account is active.

bash-3.2$ !539
gcloud auth list
             Credentialed Accounts
ACTIVE  ACCOUNT
*       asurjit@amar1979.iam.gserviceaccount.com

To set the active account, run:
    $ gcloud config set account `ACCOUNT`

Please suggest what I am doing wrong over here.

**Comment by kurtisvg** [comment] 2019-06-12 18:05
Hi @asurjit79,

It looks like you are using user credentials. You can use `gcloud auth activate-service-account [ACCOUNT] --key-file=KEY_FILE` to specify a service account instead.

**Comment by asurjit79** [comment] 2019-06-12 18:23
Thanks @Kurtisvg for your response. I used that as well and set the account name to my service account using the above mentioned command but it didn’t make much difference when I got the same error still.

**Comment by kurtisvg** [comment] 2019-06-12 19:38
@asurjit79 Did you still get the same message about using user credentials vs service account?

And just to confirm, you are referring to java-docs-samples/speech/cloud-client/src/main/java/com/example/speech/QuickstartSample.java?

**Comment by asurjit79** [comment] 2019-06-12 21:23
yes @kurtisvg, we are referring about QuickstartSample.java itself.

I think, the error message was same for both user credentials and service account but I will give it one more try. 

And would like to paste bit more information about the earlier reply.

bash-3.2$ gcloud auth activate-service-account asurjit79@feisty-etching-243514.iam.gserviceaccount.com --key-file=/Users/asurjit/Downloads/feisty-etching-243514-50537d59011c.json 
Activated service account credentials for: [asurjit79@feisty-etching-243514.iam.gserviceaccount.com]

**Comment by kurtisvg** [comment] 2019-06-12 21:44
Ok, so I checked the project_number in your original error, and the problem is definitely related to the wrong credentials. So let's try to debug what is going wrong. 

How are you executing this code? Can you add the following lines at the top of the QuickStart:
```
GoogleCredentials credentials = GoogleCredentials.fromStream(new FileInputStream("/path/to/credentials.json"));

// Instantiates a client
try (SpeechClient speechClient = SpeechClient.create(credentials)) {
```

This should (hopefully?) be a full proof way to make sure we are getting the correct credentials.

**Comment by asurjit79** [comment] 2019-06-12 22:00
Thanks @kurtisvg. SpeechClient.create method is complaining as it is not able to accept GoogleCredentials but looking for SpeechSettings.

**"The method create(SpeechSettings) in the type SpeechClient is not applicable for the arguments (GoogleCredentials)"**

**Comment by asurjit79** [comment] 2019-06-12 22:06
I am running this from the eclipse IDE itself..anything different I need to use

**Comment by kurtisvg** [comment] 2019-06-12 23:18
Nope the IDE is fine - one easy mistake to make is setting environment variables in a terminal and then not getting them then you run your code in Eclipse. You have to specify them in the IDE as shown in this [SO post](https://stackoverflow.com/a/12810433/9414803). 

I messed up on the snippet I gave you before, the Speech library specifies credentials like this:

```
    GoogleCredentials credentials = GoogleCredentials.getApplicationDefault();
    System.out.println(credentials);

    SpeechSettings speechSettings =
        SpeechSettings.newBuilder()
            .setCredentialsProvider(FixedCredentialsProvider.create(credentials))
            .build();

    // Instantiates a client
    try (SpeechClient speechClient = SpeechClient.create(speechSettings)) {
```

That should work correctly (I tested it this time). If using that doesn't fix your problem, then we know we have the right file but it's not the right credentials. Please try to generate a new one be following the steps [here](https://cloud.google.com/vision/docs/libraries#setting_up_authentication).

And - if _that_ doesn't work - come back with the stack trace and we'll see what we can figure out :)

**Comment by asurjit79** [comment] 2019-06-12 23:30
Thanks buddy! It works now. Added environment variable to the run configuration and it solved the problem. Thanks again!!

**Comment by kurtisvg** [comment] 2019-06-12 23:41
Glad we got it to work! I'm going to go ahead and close this out.

**Closed by kurtisvg** 2019-06-12 23:41 UTC
Labels: question
