### ISSUE TITLE
Use current Apache Beam SDK in Cloud Spanner sample

### ISSUE THREAD

**Issue by hegemonic** [GoogleCloudPlatform/java-docs-samples#1400] opened 2019-05-02 21:40 UTC
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/java-docs-samples/blob/1f0a55ec/dataflow/spanner-io/pom.xml#L41

### Did you change the file? If so, how?

 No

## Describe the issue

This code sample currently uses version 2.3.0 of the Apache Beam SDK. The [current version](https://beam.apache.org/get-started/downloads/) is 2.12.0.

**Comment by averikitsch** [comment] 2019-06-11 15:26
The tests are currently broken for this sample and may need to be rewritten for a new client library. Also the pom.xml needs `${apache_beam.version}` removed so dpebot can auto update the dependency.

**Comment by dmitry-fa** [comment] 2020-03-11 14:26
This problem is no longer reproducible: all existing tests pass, the latest SDK is used.
No need to remove `${apache_beam.version}` for dpe bot, because Renovate Bot handles it now.
Last PR from the bot:  https://github.com/GoogleCloudPlatform/java-docs-samples/pull/2222

The issue could be closed.

**Comment by AVaksman** [comment] 2020-03-11 14:40
Closing the issue as per @dmitry-fa comment above.
Please reopen if the issue still persists.

**Closed by AVaksman** 2020-03-11 14:40 UTC
Labels: api: spanner, type: cleanup
